article/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    
    path('detail/<int:id>', views.detail, name='detail'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addarticle/', views.addarticle, name='addarticle'),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('user/', include('user.urls')),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('articles/', views.articles, name='articles'),
    path('article/<int:id>', views.addComment, name="comment"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length = 50, verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add = True, verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank=True, null=True, verbose_name="Makaleye Fotoğraf Ekle")
    
    def __str__(self):
        return f"{self.title}"
    class Meta:
        ordering=["-created_date"]
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Makale", related_name="comments")
    comment_author = models.CharField(max_length=20, verbose_name="Yorumcu İsmi : ")
    comment_content = models.CharField(max_length=200, verbose_name="Yorum : ")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.comment_content}"
    class Meta:
        ordering=["-comment_date"]

    

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Parola", widget=forms.PasswordInput)

    



class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=3, label="Kullanıcı Adını Giriniz ")
    password = forms.CharField(max_length=20, min_length=8, label="Parola  ", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20, min_length=8, label="Parolayı Doğrula  ", widget=forms.PasswordInput)

    def clean(self):
        # program çalışmazsa üstteki kodu sil self.cleaned_data yap alttakileri
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            # forms.ValidationError olarak değiştir
            raise forms.ValidationError("Parola Doğrulama Başarısız !!!")
        values = {
            "username" : username,
            "password" : password
        }
        return values
    

article/views.py
from django.shortcuts import redirect, render, HttpResponse, get_object_or_404, reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment
from django.contrib.auth.decorators import login_required


# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")
    # get("keyword") html deki input un name= değeri
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request, "articles.html", {"articles":articles})
    articles = Article.objects.all()

    return render(request, "articles.html", {"articles":articles})

def index(request):
    return render(request, "index.html")

def about(request):
    return render(request, "about.html")

@login_required(login_url="/user/login/")
def detail(request, id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)
    yorumlar = article.comments.all()
    
    return render(request, "detail.html", {"article":article, "yorumlar":yorumlar})

@login_required(login_url="/user/login/")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        "articles":articles
    }
    return render(request, "dashboard.html", context)

@login_required(login_url="/user/login/")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    context = {
        "form":form
    }

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Makale Başarıyla Kaydedildi...")
        return redirect("dashboard")

    return render(request, "addarticle.html", context)

@login_required(login_url="/user/login/")
def updateArticle(request, id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, "Makale Başarıyla Güncellendi...")
        return redirect("dashboard")
    return render(request, "update.html", {"form":form})

@login_required(login_url="/user/login/")
def deleteArticle(request, id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.success(request, "Makale Başarıyla Silindi...")
    return redirect("dashboard")

def addComment(request, id):
    article = get_object_or_404(Article, id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author, comment_content=comment_content)
        newComment.article = article

        newComment.save()
    return redirect(f"article/{article.id}")

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from .forms import RegisterForm, LoginForm
from django.contrib import messages


# Create your views here.

def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        print(f"username : {username}\npass : {password}")
            
        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()

        login(request, newUser)
        messages.success(request, "Başarıyla Kayıt Oldunuz ...")

        return redirect("index")
    context = {
            "form" : form
            }
    return render(request, "register.html",context)

def loginUser(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username, password=password)
        if user is None:
            messages.info(request, "Kullanıcı Adı veya Parola Hatalı...")
            return render(request, "login.html", context)
        messages.success(request,"Başarıyla Giriş Yaptınız...")
        login(request, user)
        return redirect("index")

    return render(request, "login.html", context)

def logoutUser(request):
    logout(request)
    messages.success(request, "Çıkış İşlemi Başarılı...")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}

{% block title %}
    Hakkımızda
{% endblock title %}

{% block body %}
    <h3>HAKKIMIZDA</h3>
    <hr>
    biz bu dağların tepesindeyiz
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block title %}Makale Ekle{% endblock title %}

{% block body %}

{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Ekle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Kaydet</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block title %}Makaleler{% endblock title %}

{% block body %}
<h3>Makaleler</h3>
<hr>
{% if articles %}
<div class="col-lg-8">
    <form>
        {% csrf_token %}
        <input type="text" name="keyword" class="input-sm" maxlenght="64" placeholder="Ara...">
        <button type="submit" class="btn btn-danger">Ara</button>
    </form>
    <br>
</div>
{% for article in articles %}

<div class="col-lg-8">
    
    <!-- Post content-->
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <a href="{% url 'detail' article.id %}"><h1 class="fw-bolder mb-1">{{ article.title }}</h1></a>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">Posted on {{ article.created_date }}</div>
            <div class="text-muted fst-italic mb-2">by {{ article.author }}</div>
            <!-- Post categories-->
            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
        </header>
        <!-- Preview image figure-->
        {% if article.article_image %}
        <figure class="mb-4"><img class="img-fluid rounded" src="{{ article.article_image.url }}" alt=""></figure>
        {% endif %}
        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4">{{ article.content|safe|truncatewords:10 }}</p>
            <a style="float:right;" href="{% url 'detail' article.id %}" class="btn btn-primary mr-2">Devamını Oku</a>    
        </section>
        
    </article>
    <br><br>
    <hr>
</div>
{% endfor %}
{% else %}
<div class="alert alert-danger">
    Herhangi bir Makale Bulunamadı... 
</div>
{% endif %}
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block title %}
Kontrol Paneli
{% endblock title %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>

<a href="/article/addarticle" class="btn btn-primary">Makale Ekle</a>
<hr>
{% if articles %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
        
        {% for article in articles %}
        <tr>
            <th scope="row">{{ article.id }}</th>
            <td><a href="/article/article/{{ article.id }}">{{ article.title }}</a></td>
            <td>{{ article.author }}</td>
            <td>{{ article.created_date }}</td>
            <td><a href="/article/update/{{ article.id }}" class="btn btn-primary">Güncelle</a></td>
            <td><a href="/article/delete/{{ article.id }}" class="btn btn-danger">Sil</a></td>
          </tr>  
        {% endfor %}
            
      
    </tbody>
  </table>

{% else %}
<div class="alert alert-danger">
  Henüz Bir Makaleniz Bulunmuyor
</div>
{% endif %}
{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block title %}
Detay Sayfası
{% endblock title %}

{% block body %}
<div class="col-lg-8">
    <!-- Post content-->
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1">{{ article.title }}</h1>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">Posted on {{ article.created_date }}</div>
            <!--div class="text-muted fst-italic mb-2">by {{ article.author }}</div-->
            <!-- Post categories-->
            <a class="badge bg-secondary text-decoration-none link-dark" href="#!">by</a>
            <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{ article.author }}</a>
        </header>
        <!-- Preview image figure-->
        {% if article.article_image %}
        <figure class="mb-4"><img class="img-fluid rounded" src="{{ article.article_image.url }}" alt=""></figure>
        {% endif %}
        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4">{{ article.content|safe }}</p>
            
        </section>
    </article>
    
    <!--comment-->
    <section class="mb-5">
        <div class="card bg-light">
            <div class="card-body">
                
                {% if yorumlar %}
                {% for yorum in yorumlar %}
                <div class="d-flex mb-4">
                    <!-- Parent comment-->
                    <div class="flex-shrink-0"><img style="width:50px;height:50px" class="rounded-circle" src="https://www.noktalamaisaretleri.gen.tr/images/soru-isareti(1).jpg" alt="..."></div>
                    <div class="ms-3">
                        <div class="fw-bold"><small>{{ yorum.comment_author }}</small></div>
                        <div class="fw-bold"><small>{{ yorum.comment_date }}</small></div>
                        {{ yorum.comment_content}} 
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <div class="alert alert-warning">Bu Makaleye Henüz Yorum Yapılmamış. İlk Yorum Yapan Siz Olmak İster misiniz?</div>
                {% endif %}
                <!-- Comment form-->
                <form class="mb-4" action="{% url 'comment' article.id %}" method="post">
                    {% csrf_token %}
                    <input name="comment_author" type="text" class="form-control" placeholder="İsminiz :">
                    <textarea name="comment_content" class="form-control mt-2" rows="3" placeholder="Yorum Yaptığınız İçin Teşekkür Ederiz..."></textarea>
                    <button type="submit" class="btn btn-danger mb-3 mt-2">Yorum Ekle</button>
                </form> 
            </div>
        </div>
    </section>
</div>
{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index' %}">BLOG</a>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'articles' %}">Makaleler</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
        
      </ul>
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link " href="#"><small>HOŞGELDİN </small><mark>{{ request.user.username }}</mark></a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'dashboard' %}">Kontrol Paneli</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'user:logout' %}">Çıkış Yap</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'user:login' %}">Giriş Yap</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'user:register' %}">Kayıt Ol</a>
        </li>
        {% endif %}        
    </div>
</nav>

templates/includes/posttemplate.html
<div class="col-lg-8">
    <!-- Post content-->
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">Posted on January 1, 2023 by Start Bootstrap</div>
            <!-- Post categories-->
            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
        </header>
        <!-- Preview image figure-->
        <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..."></figure>
        <!-- Post content-->
        <section class="mb-5">
            <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
            <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
            <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
            <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
            <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
            <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
        </section>
    </article>
    <!-- Comments section-->
    <section class="mb-5">
        <div class="card bg-light">
            <div class="card-body">
                <!-- Comment form-->
                <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                <!-- Comment with nested comments-->
                <div class="d-flex mb-4">
                    <!-- Parent comment-->
                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                    <div class="ms-3">
                        <div class="fw-bold">Commenter Name</div>
                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                        <!-- Child comment 1-->
                        <div class="d-flex mt-4">
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                            <div class="ms-3">
                                <div class="fw-bold">Commenter Name</div>
                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                            </div>
                        </div>
                        <!-- Child comment 2-->
                        <div class="d-flex mt-4">
                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                            <div class="ms-3">
                                <div class="fw-bold">Commenter Name</div>
                                When you put money directly to a problem, it makes a good headline.
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Single comment-->
                <div class="d-flex">
                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                    <div class="ms-3">
                        <div class="fw-bold">Commenter Name</div>
                        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

templates/index.html
{% extends "layout.html" %}

{% block title %}
    Anasayfa
{% endblock title %}

{% block body %}
    <div class="jumbotron text-center">
        <h3>Yazılım Bloğuna Hoşgeldiniz</h3>
        <p>Deneme Amaçlı Yazılmıştır</p>
    </div>
{% endblock body %}

templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div style = "margin-top : 10px; margin-bootom : 50px" class = "container">
        {% include 'includes/navbar.html' %}
        {% if messages %}
          
              {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
              {% endfor %}
          
        {% endif %}
        
        {% block body %}
        {% endblock body %}
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
     <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
     <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script> -->

     <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
     <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
     <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block title %}
Giriş Yap
{% endblock title %}


{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>
    </div>
</div>



{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block title %}
Kayıt Ol
{% endblock title %}
{% load crispy_forms_tags %}

{% block body %}
<h3>Kayıt Ol</h3>
<hr>

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-primary">Kayıt Ol</button>
</form>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block title %}Güncelle{% endblock title %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Güncelle</button>
        </form>
    </div>
</div>
{% endblock body %}